name: CHEWX
highlighter: rouge
markdown: kramdown
permalink: '/:year/:title/'
paginate_path: '/page:num/'
exclude: [bower_components]
paginate: 10
sass:
  sass_dir: assets/css/scss
  style: :compressed
gems: [jekyll-paginate]

